namespace savings_sage.Model;

public class CurrencyMapper
{
    private static readonly Dictionary<Currency, string> currencyNames = new Dictionary<Currency, string>{
        { Currency.AED, "Emirátusi dirham" } ,
        { Currency.AFN, "Afgán afgáni" } ,
        { Currency.ALL, "Albán lek" } ,
        { Currency.AMD, "Örmény dram" } ,
        { Currency.ANG, "Holland antillákbeli forint" } ,
        { Currency.AOA, "Angolai kwanza" } ,
        { Currency.ARS, "Argentin peso" } ,
        { Currency.AUD, "Ausztrál dollár" } ,
        { Currency.AWG, "Arubai florin" } ,
        { Currency.AZN, "Azerbajdzsáni manat" } ,
        { Currency.BAM, "Bosnyák konvertibilis márka" } ,
        { Currency.BBD, "Barbadosi dollár" } ,
        { Currency.BDT, "Bangladesi taka" } ,
        { Currency.BGN, "Bolgár leva" } ,
        { Currency.BHD, "Bahreini dinár" } ,
        { Currency.BIF, "Burundi frank" } ,
        { Currency.BMD, "Bermudai dollár" } ,
        { Currency.BND, "Brunei dollár" } ,
        { Currency.BOB, "Bolíviai boliviano" } ,
        // { Currency.BOV, "Bolíviai mvdol" } ,
        { Currency.BRL, "Brazil real" } ,
        { Currency.BSD, "Bahamai dollár" } ,
        { Currency.BTN, "Bhutáni ngultrum" } ,
        { Currency.BWP, "Botswanai pula" } ,
        { Currency.BYR, "Fehérorosz rubel" } ,
        { Currency.BZD, "Belize-i dollár" } ,
        { Currency.CAD, "Kanadai dollár" } ,
        { Currency.CDF, "Kongói frank" } ,
        // { Currency.CHE, "WIR euró" } ,
        { Currency.CHF, "Svájci frank" } ,
        // { Currency.CHW, "WIR frank" } ,
        { Currency.CLF, "Chilei fejlesztési egység" } ,
        { Currency.CLP, "Chilei peso" } ,
        { Currency.CNY, "Kínai jüan" } ,
        { Currency.COP, "Kolumbiai peso" } ,
        // { Currency.COU, "Kolumbiai értékelési egység" } ,
        { Currency.CRC, "Costa Rica-i colón" } ,
        { Currency.CUC, "Kubai konvertibilis peso" } ,
        { Currency.CUP, "Kubai peso" } ,
        { Currency.CVE, "Zöld-foki escudo" } ,
        { Currency.CZK, "Cseh korona" } ,
        { Currency.DJF, "Dzsibuti frank" } ,
        { Currency.DKK, "Dán korona" } ,
        { Currency.DOP, "Dominikai peso" } ,
        { Currency.DZD, "Algériai dinár" } ,
        { Currency.EGP, "Egyiptomi font" } ,
        { Currency.ERN, "Eritreai nakfa" } ,
        { Currency.ETB, "Etiópiai birr" } ,
        { Currency.EUR, "Euró" } ,
        { Currency.FJD, "Fidzsi dollár" } ,
        { Currency.FKP, "Falkland-szigeteki font" } ,
        { Currency.GBP, "Brit font" } ,
        { Currency.GEL, "Grúz lari" } ,
        { Currency.GGP, "Guernsey font" } ,
        { Currency.GHS, "Ghánai cedi" } ,
        { Currency.GIP, "Gibraltári font" } ,
        { Currency.GMD, "Gambiai dalasi" } ,
        { Currency.GNF, "Guineai frank" } ,
        { Currency.GTQ, "Guatemalai quetzal" } ,
        { Currency.GYD, "Guyana-i dollár" } ,
        { Currency.HKD, "Hongkongi dollár" } ,
        { Currency.HNL, "Hondurasi lempira" } ,
        { Currency.HRK, "Horvát kuna" } ,
        { Currency.HTG, "Haiti gourde" } ,
        { Currency.HUF, "Magyar forint" } ,
        { Currency.IDR, "Indonéz rúpia" } ,
        { Currency.ILS, "Izraeli új sékel" } ,
        { Currency.IMP, "Manxi font" } ,
        { Currency.INR, "Indiai rúpia" } ,
        { Currency.IQD, "Iraki dinár" } ,
        { Currency.IRR, "Iráni rial" } ,
        { Currency.ISK, "Izlandi korona" } ,
        { Currency.JEP, "Jersey font" } ,
        { Currency.JMD, "Jamaicai dollár" } ,
        { Currency.JOD, "Jordán dinár" } ,
        { Currency.JPY, "Japán jen" } ,
        { Currency.KES, "Kenya-i shilling" } ,
        { Currency.KGS, "Kirgizisztáni szom" } ,
        { Currency.KHR, "Kambodzsai riel" } ,
        { Currency.KMF, "Comore-i frank" } ,
        { Currency.KPW, "Észak-koreai won" } ,
        { Currency.KRW, "Dél-koreai won" } ,
        { Currency.KWD, "Kuvaiti dinár" } ,
        { Currency.KYD, "Kajmán-szigeteki dollár" } ,
        { Currency.KZT, "Kazah tenge" } ,
        { Currency.LAK, "Laoszi kip" } ,
        { Currency.LBP, "Libanoni font" } ,
        { Currency.LKR, "Sri Lanka-i rúpia" } ,
        { Currency.LRD, "Libériai dollár" } ,
        { Currency.LSL, "Lesotho-i loti" } ,
        { Currency.LTL, "Litván lita" } ,
        { Currency.LVL, "Lett lat" } ,
        { Currency.LYD, "Líbiai dinár" } ,
        { Currency.MAD, "Marokkói dirham" } ,
        { Currency.MDL, "Moldovai lej" } ,
        { Currency.MGA, "Madagaszkári ariary" } ,
        { Currency.MKD, "Macedón dénár" } ,
        { Currency.MMK, "Mianmari kyat" } ,
        { Currency.MNT, "Mongol tugrik" } ,
        { Currency.MOP, "Makaói pataca" } ,
        { Currency.MRO, "Mauritániai ouguiya" } ,
        { Currency.MUR, "Mauritiusi rúpia" } ,
        { Currency.MVR, "Maldív rufiyaa" } ,
        { Currency.MWK, "Malawi kwacha" } ,
        { Currency.MXN, "Mexikói peso" } ,
        // { Currency.MXV, "Mexikói értékelési egység" } ,
        { Currency.MYR, "Maláj ringgit" } ,
        { Currency.MZN, "Mozambiki metical" } ,
        { Currency.NAD, "Namíbiai dollár" } ,
        { Currency.NGN, "Nigériai naira" } ,
        { Currency.NIO, "Nicaraguai córdoba" } ,
        { Currency.NOK, "Norvég korona" } ,
        { Currency.NPR, "Nepáli rúpia" } ,
        { Currency.NZD, "Új-zélandi dollár" } ,
        { Currency.OMR, "Ománi rial" } ,
        { Currency.PAB, "Panamai balboa" } ,
        { Currency.PEN, "Perui sol" } ,
        { Currency.PGK, "Pápua új-guineai kina" } ,
        { Currency.PHP, "Fülöp-szigeteki peso" } ,
        { Currency.PKR, "Pakisztáni rúpia" } ,
        { Currency.PLN, "Lengyel zloty" } ,
        { Currency.PYG, "Paraguayi guarani" } ,
        { Currency.QAR, "Katari rial" } ,
        { Currency.RON, "Román lej" } ,
        { Currency.RSD, "Szerb dinár" } ,
        { Currency.RUB, "Orosz rubel" } ,
        { Currency.RWF, "Ruandai frank" } ,
        { Currency.SAR, "Szaúd-arábiai rial" } ,
        { Currency.SBD, "Salamon-szigeteki dollár" } ,
        { Currency.SCR, "Seychelle-szigeteki rúpia" } ,
        { Currency.SDG, "Szudáni font" } ,
        { Currency.SEK, "Svéd korona" } ,
        { Currency.SGD, "Szingapúri dollár" } ,
        { Currency.SHP, "Szent Ilona-i font" } ,
        { Currency.SLL, "Sierra Leone-i leone" } ,
        { Currency.SOS, "Szomáli shilling" } ,
        { Currency.SRD, "Suriname-i dollár" } ,
        // { Currency.SSP, "Dél-szudáni font" } ,
        // { Currency.STN, "São Tomé és Príncipe-i dobra" } , //apiban STD
        { Currency.SVC, "Salvadori colón" } ,
        { Currency.SYP, "Szíriai font" } ,
        { Currency.SZL, "Szváziföldi lilangeni" } ,
        { Currency.THB, "Thaiföldi baht" } ,
        { Currency.TJS, "Tádzsikisztáni somoni" } ,
        { Currency.TMT, "Türkmenisztáni manat" } ,
        { Currency.TND, "Tunéziai dinár" } ,
        { Currency.TOP, "Tongai paanga" } ,
        { Currency.TRY, "Török líra" } ,
        { Currency.TTD, "Trinidad és Tobagói dollár" } ,
        { Currency.TWD, "Tajvani új dollár" } ,
        { Currency.TZS, "Tanzániai shilling" } ,
        { Currency.UAH, "Ukrán hrivnya" } ,
        { Currency.UGX, "Ugandai shilling" } ,
        { Currency.USD, "Amerikai dollár" } ,
        // { Currency.USN, "Amerikai dollár (következő nap)" } ,
        // { Currency.UYI, "Uruguayi peso en unidades indexadas" } ,
        { Currency.UYU, "Uruguayi peso" } ,
        { Currency.UZS, "Üzbegisztáni szom" } ,
        { Currency.VEF, "Venezuelai bolívar" } ,
        { Currency.VND, "Vietnami dong" } ,
        { Currency.VUV, "Vanuatui vatu" } ,
        { Currency.WST, "Szamoai tala" } ,
        { Currency.XAF, "Közép-afrikai CFA frank" } ,
        { Currency.XCD, "Kelet-karibi dollár" } ,
        { Currency.XDR, "Különleges lehívási jogok" } ,
        { Currency.XOF, "Nyugat-afrikai CFA frank" } ,
        { Currency.XPF, "CFP frank" } ,
        // { Currency.XSU, "SUCRE" } ,
        // { Currency.XUA, "ADB elszámolási egység" } ,
        { Currency.YER, "Jemeni rial" } ,
        { Currency.ZAR, "Dél-afrikai rand" } ,
        { Currency.ZMW, "Zambiai kwacha" } ,
        { Currency.ZWL, "Zimbabwei dollár" }
    };
    
    public static string GetCurrencyName(Currency code) {
        return currencyNames[code];
    }
}
